# redpanda.yml
version: "3.7"
name: redpanda-quickstart-one-broker
networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge
services:
  trade-producer:
    container_name: trade-producer
    build:
      context: ../services/trade-producer
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
  
  trade_to_ohlc:
    container_name: trade_to_ohlc
    build:
      context: ../services/trade_to_ohlc
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
  
  kafka_to_feature_store:
    container_name: kafka_to_feature_store
    build:
      context: ../services/kafka_to_feature_store
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092